"TOTAL_TIMESTEPS": 1e7
"NUM_ENVS": 64
"NUM_STEPS": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 8
"LR": 0.005
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.0001
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ANNEAL_LR": True
"ENV_NAME": "Asterix-MinAtar"
"TEST_LENGTH": 1000
"WANDB_LOG_DURING_TRAINING": True

TEST_DURING_TRAINING: True 
TEST_INTERVAL: 0.05 # in terms of total updates
TEST_ENVS: 128